DEBUG 2019-06-24 12:25:46,430 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/db/backends/utils.py utils.py execute 111 (0.001) SELECT @@SQL_AUTO_IS_NULL; args=None
DEBUG 2019-06-24 12:25:46,431 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/db/backends/utils.py utils.py execute 111 (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
DEBUG 2019-06-24 12:25:46,433 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/db/backends/utils.py utils.py execute 111 (0.001) SHOW FULL TABLES; args=None
DEBUG 2019-06-24 12:25:48,949 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/template/base.py base.py _resolve_lookup 872 Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/handlers/base.py", line 111, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/urls/resolvers.py", line 520, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <URLPattern list> (admin:admin) 'admin/'>], [<URLResolver <module 'mainsite.urls' from '/Users/lixingyu/SourceCode/mybolg/mainsite/urls.py'> (mainsite:mainsite) ''>, <URLPattern 'body/'>]], 'path': ''}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/template/base.py", line 829, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/template/base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/template/base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/template/base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <URLPattern list> (admin:admin) 'admin/'>
WARNING 2019-06-24 12:25:48,953 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET / HTTP/1.1" 404 2073
DEBUG 2019-06-24 12:25:57,054 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/template/base.py base.py _resolve_lookup 872 Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/handlers/base.py", line 111, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/urls/resolvers.py", line 520, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <URLPattern list> (admin:admin) 'admin/'>], [<URLResolver <module 'mainsite.urls' from '/Users/lixingyu/SourceCode/mybolg/mainsite/urls.py'> (mainsite:mainsite) ''>, <URLPattern 'body/'>]], 'path': ''}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/template/base.py", line 829, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/template/base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/template/base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/template/base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <URLPattern list> (admin:admin) 'admin/'>
WARNING 2019-06-24 12:25:57,055 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET / HTTP/1.1" 404 2073
INFO 2019-06-24 12:26:02,468 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body HTTP/1.1" 301 0
ERROR 2019-06-24 12:26:02,536 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 500 89783
DEBUG 2019-06-24 12:26:26,938 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/db/backends/utils.py utils.py execute 111 (0.003) SELECT @@SQL_AUTO_IS_NULL; args=None
DEBUG 2019-06-24 12:26:26,940 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/db/backends/utils.py utils.py execute 111 (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
DEBUG 2019-06-24 12:26:26,943 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/db/backends/utils.py utils.py execute 111 (0.003) SHOW FULL TABLES; args=None
ERROR 2019-06-24 12:26:29,403 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 500 54616
ERROR 2019-06-24 12:26:34,292 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 500 54616
ERROR 2019-06-24 12:26:40,251 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 500 54616
ERROR 2019-06-24 12:26:40,936 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 500 54616
ERROR 2019-06-24 12:26:41,517 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 500 54616
ERROR 2019-06-24 12:26:41,980 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 500 54616
ERROR 2019-06-24 12:26:42,302 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 500 54616
ERROR 2019-06-24 12:26:42,504 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 500 54616
ERROR 2019-06-24 12:26:42,689 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 500 54616
DEBUG 2019-06-24 12:27:21,695 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/db/backends/utils.py utils.py execute 111 (0.003) SELECT @@SQL_AUTO_IS_NULL; args=None
DEBUG 2019-06-24 12:27:21,697 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/db/backends/utils.py utils.py execute 111 (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
DEBUG 2019-06-24 12:27:21,701 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/db/backends/utils.py utils.py execute 111 (0.004) SHOW FULL TABLES; args=None
ERROR 2019-06-24 12:27:24,748 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 500 54658
DEBUG 2019-06-24 12:27:42,922 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/db/backends/utils.py utils.py execute 111 (0.002) SELECT @@SQL_AUTO_IS_NULL; args=None
DEBUG 2019-06-24 12:27:42,924 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/db/backends/utils.py utils.py execute 111 (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
DEBUG 2019-06-24 12:27:42,926 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/db/backends/utils.py utils.py execute 111 (0.002) SHOW FULL TABLES; args=None
INFO 2019-06-24 12:27:44,872 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 1981
DEBUG 2019-06-24 12:27:46,431 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/template/base.py base.py _resolve_lookup 872 Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/handlers/base.py", line 111, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/urls/resolvers.py", line 520, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <URLPattern list> (admin:admin) 'admin/'>], [<URLResolver <module 'mainsite.urls' from '/Users/lixingyu/SourceCode/mybolg/mainsite/urls.py'> (mainsite:mainsite) ''>, <URLPattern 'body/'>]], 'path': 'gitchat/activity/5d0a0c6e17acfc6fc61cdd9c'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/template/base.py", line 829, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/template/base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/template/base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/template/base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <URLPattern list> (admin:admin) 'admin/'>
WARNING 2019-06-24 12:27:46,433 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /gitchat/activity/5d0a0c6e17acfc6fc61cdd9c HTTP/1.1" 404 2214
INFO 2019-06-24 12:27:54,251 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 1981
INFO 2019-06-24 12:36:15,736 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 2025
INFO 2019-06-24 12:36:16,919 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 2025
INFO 2019-06-24 12:37:58,617 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 2091
DEBUG 2019-06-24 12:37:58,632 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/template/base.py base.py _resolve_lookup 872 Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/handlers/base.py", line 111, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/urls/resolvers.py", line 520, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <URLPattern list> (admin:admin) 'admin/'>], [<URLResolver <module 'mainsite.urls' from '/Users/lixingyu/SourceCode/mybolg/mainsite/urls.py'> (mainsite:mainsite) ''>, <URLPattern 'body/'>]], 'path': 'statics/mainsite/css/body.css'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/template/base.py", line 829, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/template/base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/template/base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/template/base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <URLPattern list> (admin:admin) 'admin/'>
WARNING 2019-06-24 12:37:58,633 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /statics/mainsite/css/body.css HTTP/1.1" 404 2178
INFO 2019-06-24 12:38:12,135 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 2090
INFO 2019-06-24 12:38:12,146 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 200 188
INFO 2019-06-24 12:43:17,926 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 2109
INFO 2019-06-24 12:43:17,937 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 200 476
INFO 2019-06-24 12:44:51,569 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 2109
INFO 2019-06-24 12:44:51,580 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 200 671
INFO 2019-06-24 12:46:29,900 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 2109
INFO 2019-06-24 12:46:29,912 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 200 957
INFO 2019-06-24 12:47:30,996 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 2109
INFO 2019-06-24 12:47:31,007 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 200 1181
INFO 2019-06-24 12:49:21,777 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 2109
INFO 2019-06-24 12:49:21,788 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 200 1424
INFO 2019-06-24 12:50:27,311 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 2109
INFO 2019-06-24 12:50:27,320 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 200 1570
INFO 2019-06-24 12:50:28,077 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 2109
INFO 2019-06-24 12:50:28,087 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 304 0
INFO 2019-06-24 12:51:35,596 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 2301
INFO 2019-06-24 12:51:35,607 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 200 1659
INFO 2019-06-24 12:52:58,507 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 2301
INFO 2019-06-24 12:52:58,518 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 200 1801
INFO 2019-06-24 12:55:26,416 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 2301
INFO 2019-06-24 12:55:26,427 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 200 1699
INFO 2019-06-24 12:55:36,496 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 2187
INFO 2019-06-24 12:55:36,505 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 304 0
INFO 2019-06-24 12:56:24,830 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 2181
INFO 2019-06-24 12:56:24,842 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 304 0
INFO 2019-06-24 12:58:17,184 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 2181
INFO 2019-06-24 12:58:17,195 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 200 1746
INFO 2019-06-24 13:07:23,424 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 2206
INFO 2019-06-24 13:07:23,435 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 200 1746
INFO 2019-06-24 13:10:03,029 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 2206
INFO 2019-06-24 13:10:03,039 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 304 0
INFO 2019-06-24 13:11:17,726 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 2206
INFO 2019-06-24 13:11:17,736 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 200 1777
INFO 2019-06-24 13:11:18,578 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 2206
INFO 2019-06-24 13:11:18,589 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 304 0
INFO 2019-06-24 13:12:51,863 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 2222
INFO 2019-06-24 13:12:51,875 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 304 0
INFO 2019-06-24 13:16:33,252 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 2444
INFO 2019-06-24 13:16:33,262 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 200 1811
INFO 2019-06-24 13:17:43,055 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 2444
INFO 2019-06-24 13:17:43,066 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 200 1830
INFO 2019-06-24 13:18:16,349 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 2444
INFO 2019-06-24 13:18:16,361 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 200 1825
INFO 2019-06-24 13:18:25,260 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 2444
INFO 2019-06-24 13:18:25,269 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 304 0
INFO 2019-06-24 13:18:46,909 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 2444
INFO 2019-06-24 13:18:46,919 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 200 1834
INFO 2019-06-24 13:18:51,021 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 304 0
INFO 2019-06-24 13:19:34,226 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 2444
INFO 2019-06-24 13:19:34,236 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 200 1833
INFO 2019-06-24 13:21:06,331 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 2444
INFO 2019-06-24 13:21:06,341 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 200 1852
INFO 2019-06-24 13:21:21,490 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 2444
INFO 2019-06-24 13:21:21,501 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 200 1852
INFO 2019-06-24 13:21:53,895 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 2444
INFO 2019-06-24 13:21:53,905 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 200 1853
INFO 2019-06-24 13:27:19,184 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 2444
INFO 2019-06-24 13:27:19,193 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 200 1853
INFO 2019-06-24 13:27:23,306 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 2444
INFO 2019-06-24 13:27:23,316 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 304 0
INFO 2019-06-24 13:27:38,484 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 2444
INFO 2019-06-24 13:27:38,494 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 200 1853
INFO 2019-06-24 13:28:22,234 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 2444
INFO 2019-06-24 13:28:22,243 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 200 1855
INFO 2019-06-24 13:30:09,073 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 2655
INFO 2019-06-24 13:30:09,081 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 304 0
INFO 2019-06-24 13:30:23,942 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 2655
INFO 2019-06-24 13:30:23,950 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 304 0
INFO 2019-06-24 13:31:35,397 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 2655
INFO 2019-06-24 13:31:35,407 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 200 1939
INFO 2019-06-24 13:32:11,713 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 2812
INFO 2019-06-24 13:32:11,724 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 200 1939
INFO 2019-06-24 13:32:30,064 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 2812
INFO 2019-06-24 13:32:30,074 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 200 1963
INFO 2019-06-24 13:33:16,866 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 2812
INFO 2019-06-24 13:33:16,876 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 200 2016
INFO 2019-06-24 13:34:30,140 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 2812
INFO 2019-06-24 13:34:30,149 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 200 2036
INFO 2019-06-24 13:35:29,133 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 2812
INFO 2019-06-24 13:35:29,144 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 200 2040
INFO 2019-06-24 13:36:39,410 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 2812
INFO 2019-06-24 13:36:39,421 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 200 2037
INFO 2019-06-24 13:36:56,810 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 2812
INFO 2019-06-24 13:36:56,822 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 200 2058
INFO 2019-06-24 13:37:31,739 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 2812
INFO 2019-06-24 13:37:31,750 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 200 2089
INFO 2019-06-24 13:38:11,971 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 2812
INFO 2019-06-24 13:38:11,982 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 200 2140
INFO 2019-06-24 13:39:24,824 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 2804
INFO 2019-06-24 13:39:24,835 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 200 2387
INFO 2019-06-24 13:39:48,704 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 2804
INFO 2019-06-24 13:39:48,714 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 200 2387
DEBUG 2019-06-24 13:43:46,912 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/db/backends/utils.py utils.py execute 111 (0.001) SELECT @@SQL_AUTO_IS_NULL; args=None
DEBUG 2019-06-24 13:43:46,913 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/db/backends/utils.py utils.py execute 111 (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
DEBUG 2019-06-24 13:43:46,915 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/db/backends/utils.py utils.py execute 111 (0.001) SHOW FULL TABLES; args=None
DEBUG 2019-06-24 13:44:21,106 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/db/backends/utils.py utils.py execute 111 (0.001) SELECT @@SQL_AUTO_IS_NULL; args=None
DEBUG 2019-06-24 13:44:21,107 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/db/backends/utils.py utils.py execute 111 (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
DEBUG 2019-06-24 13:44:21,108 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/db/backends/utils.py utils.py execute 111 (0.001) SHOW FULL TABLES; args=None
INFO 2019-06-24 13:44:30,048 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body HTTP/1.1" 301 0
INFO 2019-06-24 13:44:30,093 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 5278
INFO 2019-06-24 13:44:30,154 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 200 2387
DEBUG 2019-06-24 13:44:30,270 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/template/base.py base.py _resolve_lookup 872 Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/handlers/base.py", line 111, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/urls/resolvers.py", line 520, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <URLPattern list> (admin:admin) 'admin/'>], [<URLResolver <module 'mainsite.urls' from '/Users/lixingyu/SourceCode/mybolg/mainsite/urls.py'> (mainsite:mainsite) ''>, <URLPattern 'body/'>]], 'path': 'favicon.ico'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/template/base.py", line 829, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/template/base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/template/base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/template/base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <URLPattern list> (admin:admin) 'admin/'>
WARNING 2019-06-24 13:44:30,272 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /favicon.ico HTTP/1.1" 404 2129
INFO 2019-06-24 13:44:44,278 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 5278
INFO 2019-06-24 13:44:44,288 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 304 0
INFO 2019-06-24 13:45:58,311 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 5278
INFO 2019-06-24 13:45:58,365 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 304 0
DEBUG 2019-06-24 13:45:58,442 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/template/base.py base.py _resolve_lookup 872 Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/handlers/base.py", line 111, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/urls/resolvers.py", line 520, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <URLPattern list> (admin:admin) 'admin/'>], [<URLResolver <module 'mainsite.urls' from '/Users/lixingyu/SourceCode/mybolg/mainsite/urls.py'> (mainsite:mainsite) ''>, <URLPattern 'body/'>]], 'path': 'favicon.ico'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/template/base.py", line 829, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/template/base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/template/base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/template/base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <URLPattern list> (admin:admin) 'admin/'>
WARNING 2019-06-24 13:45:58,443 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /favicon.ico HTTP/1.1" 404 2129
INFO 2019-06-24 13:46:19,977 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 5278
INFO 2019-06-24 13:46:20,129 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 200 2387
DEBUG 2019-06-24 13:46:20,364 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/template/base.py base.py _resolve_lookup 872 Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/handlers/base.py", line 111, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/urls/resolvers.py", line 520, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <URLPattern list> (admin:admin) 'admin/'>], [<URLResolver <module 'mainsite.urls' from '/Users/lixingyu/SourceCode/mybolg/mainsite/urls.py'> (mainsite:mainsite) ''>, <URLPattern 'body/'>]], 'path': 'favicon.ico'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/template/base.py", line 829, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/template/base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/template/base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/template/base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <URLPattern list> (admin:admin) 'admin/'>
WARNING 2019-06-24 13:46:20,365 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /favicon.ico HTTP/1.1" 404 2129
INFO 2019-06-24 13:46:58,162 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 5278
INFO 2019-06-24 13:46:58,267 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 200 2387
DEBUG 2019-06-24 13:46:58,515 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/template/base.py base.py _resolve_lookup 872 Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/handlers/base.py", line 111, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/urls/resolvers.py", line 520, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <URLPattern list> (admin:admin) 'admin/'>], [<URLResolver <module 'mainsite.urls' from '/Users/lixingyu/SourceCode/mybolg/mainsite/urls.py'> (mainsite:mainsite) ''>, <URLPattern 'body/'>]], 'path': 'favicon.ico'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/template/base.py", line 829, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/template/base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/template/base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/template/base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <URLPattern list> (admin:admin) 'admin/'>
WARNING 2019-06-24 13:46:58,516 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /favicon.ico HTTP/1.1" 404 2129
DEBUG 2019-06-24 13:47:06,200 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/template/base.py base.py _resolve_lookup 872 Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/handlers/base.py", line 111, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/urls/resolvers.py", line 520, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <URLPattern list> (admin:admin) 'admin/'>], [<URLResolver <module 'mainsite.urls' from '/Users/lixingyu/SourceCode/mybolg/mainsite/urls.py'> (mainsite:mainsite) ''>, <URLPattern 'body/'>]], 'path': 'gitchat/activity/5d0a0c6e17acfc6fc61cdd9c'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/template/base.py", line 829, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/template/base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/template/base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/template/base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <URLPattern list> (admin:admin) 'admin/'>
WARNING 2019-06-24 13:47:06,202 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /gitchat/activity/5d0a0c6e17acfc6fc61cdd9c HTTP/1.1" 404 2219
DEBUG 2019-06-24 13:47:12,215 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/template/base.py base.py _resolve_lookup 872 Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/handlers/base.py", line 111, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/urls/resolvers.py", line 520, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <URLPattern list> (admin:admin) 'admin/'>], [<URLResolver <module 'mainsite.urls' from '/Users/lixingyu/SourceCode/mybolg/mainsite/urls.py'> (mainsite:mainsite) ''>, <URLPattern 'body/'>]], 'path': 'gitchat/activity/5d0a0c6e17acfc6fc61cdd9c'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/template/base.py", line 829, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/template/base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/template/base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/template/base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <URLPattern list> (admin:admin) 'admin/'>
WARNING 2019-06-24 13:47:12,217 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /gitchat/activity/5d0a0c6e17acfc6fc61cdd9c HTTP/1.1" 404 2219
INFO 2019-06-24 13:47:19,022 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 304 0
DEBUG 2019-06-24 13:50:17,613 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/db/backends/utils.py utils.py execute 111 (0.001) SELECT @@SQL_AUTO_IS_NULL; args=None
DEBUG 2019-06-24 13:50:17,614 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/db/backends/utils.py utils.py execute 111 (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
DEBUG 2019-06-24 13:50:17,616 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/db/backends/utils.py utils.py execute 111 (0.001) SHOW FULL TABLES; args=None
INFO 2019-06-24 13:50:22,796 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 3319
INFO 2019-06-24 13:50:22,833 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 304 0
INFO 2019-06-24 13:51:42,356 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 3319
INFO 2019-06-24 13:51:42,369 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 200 2618
INFO 2019-06-24 13:52:50,782 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 3319
INFO 2019-06-24 13:52:50,793 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 200 2963
INFO 2019-06-24 13:52:52,133 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 3319
INFO 2019-06-24 13:52:52,142 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 304 0
INFO 2019-06-24 13:53:42,770 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 3319
INFO 2019-06-24 13:53:42,780 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 200 2962
INFO 2019-06-24 13:53:44,023 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 3319
INFO 2019-06-24 13:53:44,033 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 304 0
INFO 2019-06-24 13:54:18,045 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 3276
INFO 2019-06-24 13:54:18,054 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 304 0
INFO 2019-06-24 13:54:42,361 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 3276
INFO 2019-06-24 13:54:42,371 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 200 3008
INFO 2019-06-24 13:56:40,580 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 3276
INFO 2019-06-24 13:56:40,589 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 200 3683
INFO 2019-06-24 13:56:41,328 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 3276
INFO 2019-06-24 13:56:41,337 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 304 0
INFO 2019-06-24 13:56:41,885 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 3276
INFO 2019-06-24 13:56:41,895 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 304 0
INFO 2019-06-24 13:57:28,976 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 3276
INFO 2019-06-24 13:57:28,986 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 200 3972
INFO 2019-06-24 13:58:00,448 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 3276
INFO 2019-06-24 13:58:00,457 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 304 0
INFO 2019-06-24 13:58:01,149 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 3276
INFO 2019-06-24 13:58:01,631 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 3276
INFO 2019-06-24 13:58:02,131 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 3276
INFO 2019-06-24 13:58:14,281 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 304 0
INFO 2019-06-24 13:58:59,183 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 3276
INFO 2019-06-24 13:58:59,194 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 200 4000
INFO 2019-06-24 13:59:23,029 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 3276
INFO 2019-06-24 13:59:23,041 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 200 4015
INFO 2019-06-24 14:03:46,019 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 3276
INFO 2019-06-24 14:03:46,030 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 200 4054
INFO 2019-06-24 14:05:02,906 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 3276
INFO 2019-06-24 14:05:02,920 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 200 4053
INFO 2019-06-24 14:05:52,327 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 3276
INFO 2019-06-24 14:05:52,340 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 200 4059
INFO 2019-06-24 14:06:22,191 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /body/ HTTP/1.1" 200 3276
INFO 2019-06-24 14:06:22,201 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/servers/basehttp.py basehttp.py log_message 154 "GET /static/mainsite/css/body.css HTTP/1.1" 200 4058
