WARNING 2019-06-24 12:25:48,952 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/utils/log.py log.py log_response 228 Not Found: /
WARNING 2019-06-24 12:25:57,055 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/utils/log.py log.py log_response 228 Not Found: /
ERROR 2019-06-24 12:26:02,535 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/utils/log.py log.py log_response 228 Internal Server Error: /body/
Traceback (most recent call last):
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/lixingyu/SourceCode/mybolg/mainsite/views.py", line 5, in body
    render(render,"mainsite/body.html")
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/template/base.py", line 169, in render
    with context.bind_template(self):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/template/context.py", line 246, in bind_template
    updates.update(processor(self.request))
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/template/context_processors.py", line 40, in debug
    if settings.DEBUG and request.META.get('REMOTE_ADDR') in settings.INTERNAL_IPS:
AttributeError: 'function' object has no attribute 'META'
ERROR 2019-06-24 12:26:29,402 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/utils/log.py log.py log_response 228 Internal Server Error: /body/
Traceback (most recent call last):
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/handlers/base.py", line 137, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view mainsite.views.body didn't return an HttpResponse object. It returned None instead.
ERROR 2019-06-24 12:26:34,291 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/utils/log.py log.py log_response 228 Internal Server Error: /body/
Traceback (most recent call last):
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/handlers/base.py", line 137, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view mainsite.views.body didn't return an HttpResponse object. It returned None instead.
ERROR 2019-06-24 12:26:40,250 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/utils/log.py log.py log_response 228 Internal Server Error: /body/
Traceback (most recent call last):
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/handlers/base.py", line 137, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view mainsite.views.body didn't return an HttpResponse object. It returned None instead.
ERROR 2019-06-24 12:26:40,936 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/utils/log.py log.py log_response 228 Internal Server Error: /body/
Traceback (most recent call last):
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/handlers/base.py", line 137, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view mainsite.views.body didn't return an HttpResponse object. It returned None instead.
ERROR 2019-06-24 12:26:41,517 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/utils/log.py log.py log_response 228 Internal Server Error: /body/
Traceback (most recent call last):
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/handlers/base.py", line 137, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view mainsite.views.body didn't return an HttpResponse object. It returned None instead.
ERROR 2019-06-24 12:26:41,980 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/utils/log.py log.py log_response 228 Internal Server Error: /body/
Traceback (most recent call last):
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/handlers/base.py", line 137, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view mainsite.views.body didn't return an HttpResponse object. It returned None instead.
ERROR 2019-06-24 12:26:42,302 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/utils/log.py log.py log_response 228 Internal Server Error: /body/
Traceback (most recent call last):
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/handlers/base.py", line 137, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view mainsite.views.body didn't return an HttpResponse object. It returned None instead.
ERROR 2019-06-24 12:26:42,504 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/utils/log.py log.py log_response 228 Internal Server Error: /body/
Traceback (most recent call last):
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/handlers/base.py", line 137, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view mainsite.views.body didn't return an HttpResponse object. It returned None instead.
ERROR 2019-06-24 12:26:42,688 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/utils/log.py log.py log_response 228 Internal Server Error: /body/
Traceback (most recent call last):
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/handlers/base.py", line 137, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view mainsite.views.body didn't return an HttpResponse object. It returned None instead.
ERROR 2019-06-24 12:27:24,747 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/utils/log.py log.py log_response 228 Internal Server Error: /body/
Traceback (most recent call last):
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/core/handlers/base.py", line 137, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view mainsite.views.body didn't return an HttpResponse object. It returned None instead.
WARNING 2019-06-24 12:27:46,433 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/utils/log.py log.py log_response 228 Not Found: /gitchat/activity/5d0a0c6e17acfc6fc61cdd9c
WARNING 2019-06-24 12:37:58,633 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/utils/log.py log.py log_response 228 Not Found: /statics/mainsite/css/body.css
WARNING 2019-06-24 13:44:30,272 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/utils/log.py log.py log_response 228 Not Found: /favicon.ico
WARNING 2019-06-24 13:45:58,443 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/utils/log.py log.py log_response 228 Not Found: /favicon.ico
WARNING 2019-06-24 13:46:20,365 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/utils/log.py log.py log_response 228 Not Found: /favicon.ico
WARNING 2019-06-24 13:46:58,516 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/utils/log.py log.py log_response 228 Not Found: /favicon.ico
WARNING 2019-06-24 13:47:06,201 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/utils/log.py log.py log_response 228 Not Found: /gitchat/activity/5d0a0c6e17acfc6fc61cdd9c
WARNING 2019-06-24 13:47:12,216 /Users/lixingyu/.virtualenvs/Readbook/lib/python3.7/site-packages/django/utils/log.py log.py log_response 228 Not Found: /gitchat/activity/5d0a0c6e17acfc6fc61cdd9c
